-- ============================================================
-- EarnSaga PostgreSQL Schema
-- Generated from live database
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- TABLE: users
-- ────────────────────────────────────────────────────────────
CREATE TABLE public.users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      TEXT,
    name       TEXT,
    picture    TEXT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX idx_users_email ON public.users USING btree (email);


-- ────────────────────────────────────────────────────────────
-- TABLE: wallets
-- ────────────────────────────────────────────────────────────
CREATE TABLE public.wallets (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    balance    BIGINT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX idx_wallets_user_id ON public.wallets USING btree (user_id);

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT fk_users_wallet FOREIGN KEY (user_id) REFERENCES public.users(id);


-- ────────────────────────────────────────────────────────────
-- TABLE: offers
-- ────────────────────────────────────────────────────────────
CREATE TABLE public.offers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id         TEXT,               -- PubScale offer ID (unique)
    name             TEXT,
    ic_url           TEXT,               -- Icon / image URL
    payout_usd       NUMERIC,            -- USD payout from advertiser
    inapp_pyt_amt    BIGINT,             -- Coin reward for user
    desc_raw         TEXT,               -- Offer description
    trk_url          TEXT,               -- PubScale tracking link
    off_type         TEXT,               -- 'game', 'app', 'website'
    os               TEXT,               -- 'android', 'ios', 'all'
    geo_tgt_include  JSONB,              -- Target countries []
    geo_tgt_exclude  JSONB,              -- Excluded countries []
    pubscale_upd_ts  BIGINT,             -- Last sync timestamp from PubScale
    goals            JSONB,              -- Offer goals / milestones
    created_at       TIMESTAMP WITH TIME ZONE,
    updated_at       TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX idx_offers_offer_id ON public.offers USING btree (offer_id);


-- ────────────────────────────────────────────────────────────
-- TABLE: user_offers
-- Tracks which user started / completed which offer
-- ────────────────────────────────────────────────────────────
CREATE TABLE public.user_offers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    offer_id   BIGINT,                   -- FK → offers.id
    status     TEXT,                     -- 'IN_PROGRESS' | 'COMPLETED'
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- Prevents a user from starting the same offer twice
CREATE UNIQUE INDEX idx_user_offer ON public.user_offers USING btree (user_id, offer_id);


-- ────────────────────────────────────────────────────────────
-- TABLE: transactions
-- Immutable ledger of every credit / debit
-- ────────────────────────────────────────────────────────────
CREATE TABLE public.transactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id  BIGINT,                   -- FK → wallets.id
    amount     BIGINT,                   -- Coin amount
    type       TEXT,                     -- 'CREDIT' | 'DEBIT'
    reference  TEXT,                     -- Source (e.g. 'NordVPN Completion')
    "timestamp" TIMESTAMP WITH TIME ZONE
);

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk_wallets_transactions FOREIGN KEY (wallet_id) REFERENCES public.wallets(id);


-- ────────────────────────────────────────────────────────────
-- TABLE: callback_logs
-- Audit log for every S2S postback received from PubScale.
-- pubscale_token is the deduplication key (also stored in Redis)
-- ────────────────────────────────────────────────────────────
CREATE TABLE public.callback_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pubscale_token  TEXT,                -- Unique token per postback (dedup key)
    user_id         BIGINT,
    value           NUMERIC,             -- Payout value received
    status          TEXT,                -- 'CREDITED' etc.
    created_at      TIMESTAMP WITH TIME ZONE
);

-- Prevents duplicate postbacks from being credited twice
CREATE UNIQUE INDEX idx_callback_logs_pubscale_token ON public.callback_logs USING btree (pubscale_token);
